# Generated by Django 4.2.5 on 2023-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(blank=True, max_length=60, null=True)),
                ('price', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('fact_1', models.CharField(max_length=50)),
                ('fact_2', models.CharField(max_length=50)),
                ('fact_3', models.CharField(max_length=50)),
                ('fact_4', models.CharField(max_length=50)),
                ('fact_5', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=300)),
                ('link', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('link', models.CharField(max_length=500)),
                ('menu', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('white_name_button', models.CharField(max_length=50)),
                ('white_link_button', models.CharField(max_length=500)),
                ('black_name_button', models.CharField(max_length=50)),
                ('black_link_button', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gratitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='portrait/')),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('content', models.TextField(max_length=100)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OffersBlack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('offer_1', models.TextField(max_length=100)),
                ('offer_2', models.TextField(blank=True, max_length=100, null=True)),
                ('offer_3', models.TextField(blank=True, max_length=100, null=True)),
                ('offer_4', models.TextField(blank=True, max_length=100, null=True)),
                ('offer_5', models.TextField(blank=True, max_length=100, null=True)),
                ('offer_6', models.TextField(blank=True, max_length=100, null=True)),
                ('offer_7', models.TextField(blank=True, max_length=100, null=True)),
                ('offer_8', models.TextField(blank=True, max_length=100, null=True)),
                ('offer_9', models.TextField(blank=True, max_length=100, null=True)),
                ('offer_10', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
